apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: docker-compose-default
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.appName }}
  podSelector:
    matchLabels:
      app: {{ .Values.appName }}
