apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.files.name }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      integrify.service: {{ .Values.files.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        integrify.service: {{ .Values.files.name }}
        app: {{ .Values.appName }}
    spec:
      containers:
        - env:
          {{- toYaml .Values.globalEnv | nindent 10 }}
          {{- toYaml .Values.files.env | nindent 10 }}
          envFrom:
          - secretRef:
              name: integrify-secrets
          image: "{{ .Values.image.repo }}/{{ .Values.files.repoName }}:{{ .Values.release | default  .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Values.files.name }}
          ports:
            - containerPort: {{ .Values.files.port }}
          resources:
            requests:
              cpu: {{ .Values.files.resources.requests.cpu }}
              memory: {{ .Values.files.resources.requests.memory }}
            limits:
              cpu: {{ .Values.files.resources.limits.cpu }}
              memory: {{ .Values.files.resources.limits.memory }}
          volumeMounts:
          - name: config-volume
            mountPath: /app/config  
            {{ if .Values.files.existingClaim }}      
          - name: file-storage
            mountPath: "/integrify/files"
            {{ end }}

      restartPolicy: {{ .Values.files.restart }}
      volumes:
        - name: config-volume
          configMap:
            name: integrifyconfig
        {{ if .Values.files.existingClaim }}      
        - name: file-storage
          persistentVolumeClaim:
            claimName: files-pv-claim
        {{ end }}
status: {}
