apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.forms.name }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.forms.healthcheck }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.forms.port }}
      targetPort: {{ .Values.forms.port }}
  selector:
    integrify.service: {{ .Values.forms.name }}
status:
  loadBalancer: {}
