apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.settings.name }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      integrify.service: {{ .Values.settings.name }}
  strategy: {}
  template:
    metadata:
      labels:
        integrify.service: {{ .Values.settings.name }}
        app: {{ .Values.appName }}
    spec:
      containers:
        - env:
          {{- toYaml .Values.globalEnv | nindent 10 }}
          envFrom:
          - secretRef:
              name: integrify-secrets
          image: "{{ .Values.image.repo }}/{{ .Values.settings.repoName }}:{{ .Values.release | default  .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Values.settings.name }}
          ports:
            - containerPort: {{ .Values.settings.port }}
          {{- if .Values.probes.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.settings.healthcheck }}
              port: {{ .Values.settings.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.settings.healthcheck }}
              port: {{ .Values.settings.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          {{- end }}
          resources:
            requests:
              cpu: {{ .Values.settings.resources.requests.cpu }}
              memory: {{ .Values.settings.resources.requests.memory }}
            limits:
              cpu: {{ .Values.settings.resources.limits.cpu }}
              memory: {{ .Values.settings.resources.limits.memory }}
          volumeMounts:
          - name: config-volume
            mountPath: /app/config
      restartPolicy: {{ .Values.settings.restart }}
      volumes:
        - name: config-volume
          configMap:
            name: integrifyconfig
status: {}
