apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.settings.name }}
  {{- if eq (.Values.ingress.controller | default "nginx-f5") "alb" }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.settings.healthcheck }}
  {{- else if or (eq (.Values.ingress.controller | default "nginx-f5") "gce") (eq (.Values.ingress.controller | default "nginx-f5") "gce-internal") }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    {{- if eq (.Values.serviceType | default "ClusterIP") "NodePort" }}
    cloud.google.com/backend-config: '{"default": "{{ .Values.settings.name }}-backend-config"}'
    {{- else }}
    cloud.google.com/backend-config: '{"ports": {"{{ .Values.settings.port }}": "{{ .Values.settings.name }}-backend-config"}}'
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.serviceType | default "ClusterIP" }}
  ports:
    - protocol: TCP
      port: {{ .Values.settings.port }}
      targetPort: {{ .Values.settings.port }}
  selector:
    integrify.service: {{ .Values.settings.name }}
status:
  loadBalancer: {}
