apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ssp.name }}
  {{- if eq (.Values.ingress.controller | default "nginx-f5") "alb" }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.ssp.healthcheck }}
  {{- else if or (eq (.Values.ingress.controller | default "nginx-f5") "gce") (eq (.Values.ingress.controller | default "nginx-f5") "gce-internal") }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Values.ssp.name }}-backend-config"}'
  {{- end }}
spec:
  type: {{ .Values.serviceType | default "ClusterIP" }}
  selector:
    integrify.service: {{ .Values.ssp.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.ssp.port }}
      targetPort: {{ .Values.ssp.port }}
status:
  loadBalancer: {}
