apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.coreService.name }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.coreService.replicas }}
  selector:
    matchLabels:
      integrify.service: {{ .Values.coreService.name }}
  strategy: {}
  template:
    metadata:
      labels:
        integrify.service: {{ .Values.coreService.name }}
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.coreService.name }}
          env:
          {{- toYaml .Values.globalEnv | nindent 10 }}
          {{- toYaml .Values.coreService.env | nindent 10 }}
          envFrom:
          - secretRef:
              name: integrify-secrets
          image: "{{ .Values.image.repo }}/{{ .Values.coreService.repoName }}:e511d1c"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.coreService.port }}
          volumeMounts:
          - name: config-volume
            mountPath: /app/config
          resources: {}
      restartPolicy: {{ .Values.coreService.restart }}
      volumes:
        - name: config-volume
          configMap:
            name: integrifyconfig
