apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.files.name }}
spec:
  selector:
    integrify.service: {{ .Values.files.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.files.port }}
      targetPort: {{ .Values.files.port }}
