apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.files.name }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.files.replicas}}
  selector:
    matchLabels:
      integrify.service: {{ .Values.files.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        integrify.service: {{ .Values.files.name }}
        app: {{ .Values.appName }}
    spec:
      containers:
        - envFrom:
          - secretRef:
              name: integrify-secrets
          env:
          {{- toYaml .Values.globalEnv | nindent 10 }}
          {{- toYaml .Values.files.env | nindent 10 }}
          image: "{{ .Values.image.repo }}/{{ .Values.files.repoName }}::{{ .Values.release | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Values.files.name }}
          ports:
            - containerPort: {{ .Values.files.port }}
          volumeMounts:
          - name: config-volume
            mountPath: /app/config
          - name: files-volume
            mountPath: /integrify/files
      restartPolicy: {{ .Values.files.restart }}
      volumes:
        - name: config-volume
          configMap:
            name: integrifyconfig
        - name: files-volume
          hostPath:
            path: /host/files 
