apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.integrations.name }}
spec:
  selector:
    integrify.service: {{ .Values.integrations.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.integrations.port }}
      targetPort: {{ .Values.integrations.port }}
