apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.reports.name }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.reports.replicas }}
  selector:
    matchLabels:
      integrify.service: {{ .Values.reports.name }}
  strategy: {}
  template:
    metadata:
      labels:
        integrify.service: {{ .Values.reports.name }}
        app: {{ .Values.appName }}
    spec:
      containers:
        - envFrom:
          - secretRef:
              name: integrify-secrets
          env:
          {{- toYaml .Values.globalEnv | nindent 10 }}
          image: "{{ .Values.image.repo }}/{{ .Values.reports.repoName }}::{{ .Values.release | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Values.reports.name }}
          ports:
            - containerPort: {{ .Values.reports.port }}
          volumeMounts:
          - name: config-volume
            mountPath: /app/config
          resources: {}
      restartPolicy: {{ .Values.reports.restart }}
      volumes:
        - name: config-volume
          configMap:
            name: integrifyconfig
