apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.settings.name }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.settings.port }}
      targetPort: {{ .Values.settings.port }}
  selector:
    integrify.service: {{ .Values.settings.name }}
