apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: integrify-eks-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # Health Check Settings
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP 
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    #alb.ingress.kubernetes.io/healthcheck-path: /healthcheck
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    #HTTPS/Certificate settings
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:564858915116:certificate/2cd99a4a-2a74-4445-8ea1-1f5bec587c2c
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
    - http:
        paths:
          - path: /workflow/napi
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.client.name }}
                port:
                  number: {{ .Values.client.port }}
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.client.name }}
                port:
                  number: {{ .Values.client.port }}
          - path: /workflow/rest-service
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.client.name }}
                port:
                  number: {{ .Values.client.port }}
          - path: /workflow/api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.client.name }}
                port:
                  number: {{ .Values.client.port }}
          - path: /access
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.client.name }}
                port:
                  number: {{ .Values.client.port }}
          - path: /files
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.client.name }}
                port:
                  number: {{ .Values.client.port }}
          - path: /instances
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.client.name }}
                port:
                  number: {{ .Values.client.port }}
          - path: /processes
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.client.name }}
                port:
                  number: {{ .Values.client.port }}
          - path: /reports
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.client.name }}
                port:
                  number: {{ .Values.client.port }}
          - path: /tasktypes
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.client.name }}
                port:
                  number: {{ .Values.client.port }}
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.client.name }}
                port:
                  number: {{ .Values.client.port }}
          - path: /core-service
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.coreService.name }}
                port:
                  number: {{ .Values.coreService.port }}
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.auth.name }}
                port:
                  number: {{ .Values.auth.port }}
          - path: /api/dashboards
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.dashboards.name }}
                port:
                  number: {{ .Values.dashboards.port }}
          - path: /api/files
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.files.name }}
                port:
                  number: {{ .Values.files.port }}
          - path: /api/forms
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.forms.name }}
                port:
                  number: {{ .Values.forms.port }}
          - path: /api/instance
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.instance.name }}
                port:
                  number: {{ .Values.instance.port }}
          - path: /api/integrations
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.integrations.name }}
                port:
                  number: {{ .Values.integrations.port }}
          - path: /api/processes
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.processes.name }}
                port:
                  number: {{ .Values.processes.port }}
          - path: /api/reports
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.reports.name }}
                port:
                  number: {{ .Values.reports.port }}
          - path: /api/schedulers
            pathType: Prefix
            backend:
              service:
                name: scheduler
                port:
                  number: 3504
          - path: /api/settings
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.settings.name }}
                port:
                  number: {{ .Values.settings.port }}
          - path: /api/task-dispatcher
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.taskDispatcher.name }}
                port:
                  number: {{ .Values.taskDispatcher.port }}
          - path: /api/tenant
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.tenant.name }}
                port:
                  number: {{ .Values.tenant.port }}
          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.user.name }}
                port:
                  number: {{ .Values.user.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ssp.name }}
                port:
                  number: {{ .Values.ssp.port }}