apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.taskProcessor.name }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      integrify.service: {{ .Values.taskProcessor.name }}
  strategy: {}
  template:
    metadata:
      labels:
        integrify.service: {{ .Values.taskProcessor.name }}
        app: {{ .Values.appName }}
    spec:
      containers:
        - env:
          {{- toYaml .Values.globalEnv | nindent 10 }}
          envFrom:
          - secretRef:
              name: integrify-secrets
          image: "{{ .Values.imageRepo }}/{{ .Values.taskProcessor.name }}:{{ .Values.taskProcessor.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Values.taskProcessor.name }}
          resources:
            requests:
              cpu: {{ .Values.taskProcessor.resources.requests.cpu }}
              memory: {{ .Values.taskProcessor.resources.requests.memory }}
            limits:
              cpu: {{ .Values.taskProcessor.resources.limits.memory }}
              memory: {{ .Values.taskProcessor.resources.limits.memory }}
      restartPolicy: {{ .Values.taskProcessor.restart }}
status: {}
